/*
 * Copyright (c) 2014-2026 Syntronix AI Corp. All rights reserved.
 * Software License Agreement
 * 
 * 
 * THIS SOFTWARE IS PROVIDED "AS IS" AND WITH ALL FAULTS.
 * NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
 * NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. TI SHALL NOT, UNDER ANY
 * CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
 * DAMAGES, FOR ANY REASON WHATSOEVER.
 *
 * @file     eh2.h
 * @brief    CMSIS HeaderFile
 * @version  1.4
 * @date     Wed Sep  2 09:46:05 2026
 * @note     Generated by SVDConv V3.3.50
 *           from File '/data/project/syntronix/FW/22_VEERWOLF_FPGA/svd_v1/eh2.svd',
 *           last modified on Wed Sep  2 09:46:05 2026
 */


/** @addtogroup Syntronix Corp.
  * @{
  */


/** @addtogroup eh2
  * @{
  */


#ifndef EH2_H
#define EH2_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup Configuration_of_CMSIS
  * @{
  */



/* =========================================================================================================================== */
/* ================                                Interrupt Number Definition                                ================ */
/* =========================================================================================================================== */

typedef enum {
/* ===========================================  other Specific Interrupt Numbers  ============================================ */
/* ============================================  eh2 Specific Interrupt Numbers  ============================================= */
  UART_IRQn                 =   1,              /*!< 1  UART Interrupt Output Signal                                           */
  SPI_IRQn                  =   2,              /*!< 2  SPI Interrupt Output Signal                                            */
  SOFT3_IRQn                =   3,              /*!< 3  Software3 Interrupt vector number                                      */
  SOFT4_IRQn                =   4,              /*!< 4  Software4 Interrupt vector number                                      */
  TIMER1_IRQn               =  28,              /*!< 28 Internal Timer1 Interrupt vector number                                */
  TIMER0_IRQn               =  29               /*!< 29 Internal Timer0 Interrupt vector number                                */
} IRQn_Type;



/* =========================================================================================================================== */
/* ================                           Processor and Core Peripheral Section                           ================ */
/* =========================================================================================================================== */
/** @} */ /* End of group Configuration_of_CMSIS */

#include "core_eh2.h"                         /*!< other processor and core peripherals                                      */
#include "system_eh2.h"                         /*!< eh2 System                                                                */

#ifndef __IM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __IM   __I
#endif
#ifndef __OM                                    /*!< Fallback for older CMSIS versions                                         */
  #define __OM   __O
#endif
#ifndef __IOM                                   /*!< Fallback for older CMSIS versions                                         */
  #define __IOM  __IO
#endif


/* ========================================  Start of section using anonymous unions  ======================================== */
#if defined (__CC_ARM)
  #pragma push
  #pragma anon_unions
#elif defined (__ICCARM__)
  #pragma language=extended
#elif defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050)
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wc11-extensions"
  #pragma clang diagnostic ignored "-Wreserved-id-macro"
  #pragma clang diagnostic ignored "-Wgnu-anonymous-struct"
  #pragma clang diagnostic ignored "-Wnested-anon-types"
#elif defined (__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined (__TMS470__)
  /* anonymous unions are enabled by default */
#elif defined (__TASKING__)
  #pragma warning 586
#elif defined (__CSMC__)
  /* anonymous unions are enabled by default */
#else
  #warning Not supported compiler type
#endif


/* =========================================================================================================================== */
/* ================                            Device Specific Peripheral Section                             ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                          SYSCON                                           ================ */
/* =========================================================================================================================== */


/**
  * @brief System Controller Peripheral for VeeRwolf SoC (SYSCON)
  */

typedef struct {                                /*!< SYSCON Structure                                                          */
  
  union {
    __IM  uint8_t VERSION_PATCH;                /*!< VeeRwolf patch version                                                    */
    
    struct {
      __IM  uint8_t PATCH       : 8;            /*!< Patch version number                                                      */
    } VERSION_PATCH_b;
  } ;
  
  union {
    __IM  uint8_t VERSION_MINOR;                /*!< VeeRwolf minor version                                                    */
    
    struct {
      __IM  uint8_t MINOR       : 8;            /*!< Minor version number                                                      */
    } VERSION_MINOR_b;
  } ;
  
  union {
    __IM  uint8_t VERSION_MAJOR;                /*!< VeeRwolf major version                                                    */
    
    struct {
      __IM  uint8_t MAJOR       : 8;            /*!< Major version number                                                      */
    } VERSION_MAJOR_b;
  } ;
  
  union {
    __IM  uint8_t VERSION_MISC;                 /*!< VeeRwolf misc version info                                                */
    
    struct {
      __IM  uint8_t REV         : 7;            /*!< Revision since last patch version                                         */
      __IM  uint8_t MODIFIED    : 1;            /*!< Set when VeeRwolf was built from modified sources                         */
    } VERSION_MISC_b;
  } ;
  
  union {
    __IM  uint32_t VERSION_SHA;                 /*!< SHA hash of the build                                                     */
    
    struct {
      __IM  uint32_t SHA        : 32;           /*!< Build SHA hash                                                            */
    } VERSION_SHA_b;
  } ;
  
  union {
    __OM  uint8_t SIM_PRINT;                    /*!< Outputs a character in simulation. No effect on hardware                  */
    
    struct {
      __OM  uint8_t CHAR        : 8;            /*!< Character output to simulation console                                    */
    } SIM_PRINT_b;
  } ;
  
  union {
    __OM  uint8_t SIM_EXIT;                     /*!< Exits a simulation. No effect on hardware                                 */
    
    struct {
      __OM  uint8_t EXIT_CODE   : 8;            /*!< Simulation exit code                                                      */
    } SIM_EXIT_b;
  } ;
  
  union {
    __IM  uint8_t INIT_STATUS;                  /*!< RAM Initialization Status                                                 */
    
    struct {
      __IM  uint8_t RAM_INIT_DONE : 1;          /*!< RAM initialization complete                                               */
      __IM  uint8_t RAM_INIT_ERR : 1;           /*!< RAM initialization reported errors                                        */
            uint8_t             : 6;
    } INIT_STATUS_b;
  } ;
  
  union {
    __IOM uint8_t SW_IRQ;                       /*!< Software-controlled external interrupts                                   */
    
    struct {
      __IOM uint8_t SW_IRQ      : 8;            /*!< Software interrupt bits                                                   */
    } SW_IRQ_b;
  } ;
  
  union {
    __IOM uint32_t NMI_VEC;                     /*!< Interrupt vector for NMI                                                  */
    
    struct {
      __IOM uint32_t VEC        : 32;           /*!< NMI vector address                                                        */
    } NMI_VEC_b;
  } ;
  
  union {
    __IOM uint32_t GPIO0;                       /*!< 32 readable and writable GPIO bits                                        */
    
    struct {
      __IOM uint32_t PINS       : 32;           /*!< GPIO0 pins state/control                                                  */
    } GPIO0_b;
  } ;
  __IM  uint32_t  RESERVED;
  
  union {
    __IOM uint32_t GPIO1;                       /*!< 32 readable and writable GPIO bits                                        */
    
    struct {
      __IOM uint32_t PINS       : 32;           /*!< GPIO1 pins state/control                                                  */
    } GPIO1_b;
  } ;
  __IM  uint32_t  RESERVED1;
  __IOM uint64_t  MTIME;                       /*!< mtime from RISC-V privilege spec                                          */
  __IOM uint64_t  MTIMECMP;                    /*!< mtimecmp from RISC-V privilege spec                                       */
  
  union {
    __IOM uint32_t IRQ_TIMER_CNT;               /*!< IRQ timer counter                                                         */
    
    struct {
      __IOM uint32_t CNT        : 32;           /*!< IRQ timer count value                                                     */
    } IRQ_TIMER_CNT_b;
  } ;
  
  union {
    __IOM uint8_t IRQ_TIMER_CTRL;               /*!< IRQ timer control                                                         */
    
    struct {
      __IOM uint8_t CTRL        : 8;            /*!< IRQ timer control flags                                                   */
    } IRQ_TIMER_CTRL_b;
  } ;
  __IM  uint8_t   RESERVED2;
  __IM  uint16_t  RESERVED3;
  __IM  uint32_t  RESERVED4;
  __IM  uint32_t  CLK_FREQ_HZ;                  /*!< Clock frequency of main clock in Hz                                       */
} SYSCON_Type;                                  /*!< Size = 64 (0x40)                                                          */



/* =========================================================================================================================== */
/* ================                                            SPI                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief Serial Peripheral Interface (SPI) with Union/Aliasing Registers (SPI)
  */

typedef struct {                                /*!< SPI Structure                                                             */
  
  union {
    __IOM uint32_t CR;                          /*!< Simple SPI Control register                                               */
    
    struct {
      __IOM uint32_t SPR        : 2;            /*!< SPI Clock Rate Select                                                     */
      __IOM uint32_t CPHA       : 1;            /*!< Clock Phase                                                               */
      __IOM uint32_t CPOL       : 1;            /*!< Clock Polarity                                                            */
      __IOM uint32_t MSTR       : 1;            /*!< Master Mode Select                                                        */
            uint32_t            : 1;
      __IOM uint32_t SPE        : 1;            /*!< Serial Peripheral Enable                                                  */
      __IOM uint32_t SPIE       : 1;            /*!< Serial Peripheral Interrupt Enable                                        */
            uint32_t            : 24;
    } CR_b;
  } ;
  __IM  uint32_t  RESERVED;
  
  union {
    __IOM uint32_t SR;                          /*!< Simple SPI status register                                                */
    
    struct {
      __IOM uint32_t RFEMPTY    : 1;            /*!< Read FIFO Empty                                                           */
      __IOM uint32_t RFFULL     : 1;            /*!< Read FIFO Full                                                            */
      __IOM uint32_t WFEMPTY    : 1;            /*!< Write FIFO Empty                                                          */
      __IOM uint32_t WFFULL     : 1;            /*!< Write FIFO Full                                                           */
            uint32_t            : 2;
      __IOM uint32_t WCOL       : 1;            /*!< Write Collision Flag                                                      */
      __IOM uint32_t SPIF       : 1;            /*!< Serial Peripheral Interrupt Flag                                          */
            uint32_t            : 24;
    } SR_b;
  } ;
  __IM  uint32_t  RESERVED1;
  __IOM uint32_t  DR;                           /*!< Simple SPI data register                                                  */
  __IM  uint32_t  RESERVED2;
  
  union {
    __IOM uint32_t ER;                          /*!< Simple SPI extended register                                              */
    
    struct {
      __IOM uint32_t ESPR       : 2;            /*!< Extended SPI Clock Rate Select
                                                     00 SPR is used to generate the SPI clock 
                                                     01 SPR is multiplied by 2 to generate the SPI clock 
                                                     10 SPR is multiplied by 4 to generate the SPI clock 
                                                     11 SPR is multiplied by 8 to generate the SPI clock                       */
            uint32_t            : 4;
      __IOM uint32_t ICNT       : 2;            /*!< Interrupt Count
                                                     00 SPIF is set after every completed transfer 
                                                     01 SPIF is set after every two completed transfers 
                                                     10 SPIF is set after every three completed transfers 
                                                     11 SPIF is set after every four completed transfers                       */
            uint32_t            : 24;
    } ER_b;
  } ;
  __IM  uint32_t  RESERVED3;
  __IOM uint32_t  SS;                           /*!< Simple SPI slave select register                                          */
} SPI_Type;                                     /*!< Size = 36 (0x24)                                                          */



/* =========================================================================================================================== */
/* ================                                           UART                                            ================ */
/* =========================================================================================================================== */


/**
  * @brief UART16550 IP Core with Wishbone Interface (UART)
  */

typedef struct {                                /*!< UART Structure                                                            */
  
  union {
    union {
      __IM  uint8_t RBR;                        /*!< Receiver Buffer Register (Read Only, DLAB=0)                              */
      
      struct {
        __IM  uint8_t RBR       : 8;            /*!< Receiver FIFO output byte                                                 */
      } RBR_b;
    } ;
    
    union {
      __OM  uint8_t THR;                        /*!< Transmitter Holding Register (Write Only, DLAB=0)                         */
      
      struct {
        __OM  uint8_t THR       : 8;            /*!< Transmit FIFO input byte                                                  */
      } THR_b;
    } ;
    
    union {
      __IOM uint8_t DLL;                        /*!< Divisor Latch Byte 1 LSB (Read/Write, DLAB=1)                             */
      
      struct {
        __IOM uint8_t DLL       : 8;            /*!< The LSB of the divisor latch                                              */
      } DLL_b;
    } ;
  };
  __IM  uint8_t   RESERVED;
  __IM  uint16_t  RESERVED1;
  
  union {
    union {
      __IOM uint8_t IER;                        /*!< Interrupt Enable Register (Read/Write, DLAB=0)                            */
      
      struct {
        __IOM uint8_t ERBFI     : 1;            /*!< Enable Received Data Available Interrupt                                  */
        __IOM uint8_t ETBEI     : 1;            /*!< Enable Transmitter Holding Register Empty Interrupt                       */
        __IOM uint8_t ELSI      : 1;            /*!< Enable Receiver Line Status Interrupt                                     */
        __IOM uint8_t EDSSI     : 1;            /*!< Enable Modem Status Interrupt                                             */
              uint8_t           : 4;
      } IER_b;
    } ;
    
    union {
      __IOM uint8_t DLM;                        /*!< Divisor Latch Byte 2 MSB (Read/Write, DLAB=1)                             */
      
      struct {
        __IOM uint8_t DLM       : 8;            /*!< The MSB of the divisor latch                                              */
      } DLM_b;
    } ;
  };
  __IM  uint8_t   RESERVED2;
  __IM  uint16_t  RESERVED3;
  
  union {
    union {
      __IM  uint8_t IIR;                        /*!< Interrupt Identification Register (Read Only)                             */
      
      struct {
        __IM  uint8_t IPEND     : 1;            /*!< Interrupt Pending ('0': Pending, '1': No interrupt pending)               */
        __IM  uint8_t INTID     : 3;            /*!< Interrupt Identification ID                                               */
              uint8_t           : 2;
        __IM  uint8_t FIFOEN    : 2;            /*!< FIFOs Enabled indicator (Fixed logic '11')                                */
      } IIR_b;
    } ;
    
    union {
      __OM  uint8_t FCR;                        /*!< FIFO Control Register (Write Only)                                        */
      
      struct {
        __OM  uint8_t FIFOEN    : 1;            /*!< FIFO Enable (Ignored in core)                                             */
        __OM  uint8_t RCVRCLR   : 1;            /*!< Receiver FIFO Clear                                                       */
        __OM  uint8_t XMITCLR   : 1;            /*!< Transmitter FIFO Clear                                                    */
              uint8_t           : 3;
        __OM  uint8_t RXTRIG    : 2;            /*!< Receiver FIFO Interrupt Trigger Level ('00':1B, '01':4B, '10':8B,
                                                     '11':14B)                                                                 */
      } FCR_b;
    } ;
  };
  __IM  uint8_t   RESERVED4;
  __IM  uint16_t  RESERVED5;
  
  union {
    __IOM uint8_t LCR;                          /*!< Line Control Register (Read/Write)                                        */
    
    struct {
      __IOM uint8_t WLS         : 2;            /*!< Word Length Select ('00':5b, '01':6b, '10':7b, '11':8b)                   */
      __IOM uint8_t STB         : 1;            /*!< Stop Bit Select                                                           */
      __IOM uint8_t PEN         : 1;            /*!< Parity Enable                                                             */
      __IOM uint8_t EPS         : 1;            /*!< Even Parity Select                                                        */
      __IOM uint8_t SP          : 1;            /*!< Stick Parity                                                              */
      __IOM uint8_t BC          : 1;            /*!< Break Control                                                             */
      __IOM uint8_t DLAB        : 1;            /*!< Divisor Latch Access Bit                                                  */
    } LCR_b;
  } ;
  __IM  uint8_t   RESERVED6;
  __IM  uint16_t  RESERVED7;
  
  union {
    __OM  uint8_t MCR;                          /*!< Modem Control Register (Write Only)                                       */
    
    struct {
      __OM  uint8_t DTR         : 1;            /*!< Data Terminal Ready Control                                               */
      __OM  uint8_t RTS         : 1;            /*!< Request To Send Control                                                   */
      __OM  uint8_t OUT1        : 1;            /*!< Out1 Output Control                                                       */
      __OM  uint8_t OUT2        : 1;            /*!< Out2 Output Control                                                       */
      __OM  uint8_t LOOP        : 1;            /*!< Loopback Mode Select                                                      */
            uint8_t             : 3;
    } MCR_b;
  } ;
  __IM  uint8_t   RESERVED8;
  __IM  uint16_t  RESERVED9;
  
  union {
    __IM  uint8_t LSR;                          /*!< Line Status Register (Read Only)                                          */
    
    struct {
      __IM  uint8_t DR          : 1;            /*!< Data Ready Indicator                                                      */
      __IM  uint8_t OE          : 1;            /*!< Overrun Error Indicator                                                   */
      __IM  uint8_t PE          : 1;            /*!< Parity Error Indicator                                                    */
      __IM  uint8_t FE          : 1;            /*!< Framing Error Indicator                                                   */
      __IM  uint8_t BI          : 1;            /*!< Break Interrupt Indicator                                                 */
      __IM  uint8_t THRE        : 1;            /*!< Transmitter Holding Register Empty Indicator                              */
      __IM  uint8_t TEMT        : 1;            /*!< Transmitter Empty Indicator                                               */
      __IM  uint8_t FIFOERR     : 1;            /*!< Error in Receiver FIFO Indicator                                          */
    } LSR_b;
  } ;
  __IM  uint8_t   RESERVED10;
  __IM  uint16_t  RESERVED11;
  
  union {
    __IM  uint8_t MSR;                          /*!< Modem Status Register (Read Only)                                         */
    
    struct {
      __IM  uint8_t DCTS        : 1;            /*!< Delta Clear To Send Indicator                                             */
      __IM  uint8_t DDSR        : 1;            /*!< Delta Data Set Ready Indicator                                            */
      __IM  uint8_t TERI        : 1;            /*!< Trailing Edge Ring Indicator Detector                                     */
      __IM  uint8_t DDCD        : 1;            /*!< Delta Data Carrier Detect Indicator                                       */
      __IM  uint8_t CTS         : 1;            /*!< Complement of CTS input (or RTS in Loopback)                              */
      __IM  uint8_t DSR         : 1;            /*!< Complement of DSR input (or DTR in Loopback)                              */
      __IM  uint8_t RI          : 1;            /*!< Complement of RI input (or Out1 in Loopback)                              */
      __IM  uint8_t DCD         : 1;            /*!< Complement of DCD input (or Out2 in Loopback)                             */
    } MSR_b;
  } ;
  __IM  uint8_t   RESERVED12;
  __IM  uint16_t  RESERVED13;
  __IM  uint32_t  RESERVED14;
  
  union {
    __IM  uint32_t DEBUG1;                      /*!< Debug Register 1 (Read Only, 32-bit mode)                                 */
    
    struct {
      __IM  uint32_t LSR_VAL    : 8;            /*!< Line Status Register value                                                */
      __IM  uint32_t IER_VAL    : 4;            /*!< Interrupt Enable Register value (bits 3-0)                                */
      __IM  uint32_t IIR_VAL    : 4;            /*!< Interrupt Identifier Register value (bits 3-0)                            */
      __IM  uint32_t LCR_VAL    : 8;            /*!< Line Control Register value                                               */
      __IM  uint32_t MSR_VAL    : 8;            /*!< Modem Status Register value                                               */
    } DEBUG1_b;
  } ;
  
  union {
    __IM  uint32_t DEBUG2;                      /*!< Debug Register 2 (Read Only, 32-bit mode)                                 */
    
    struct {
      __IM  uint32_t TX_FSM     : 3;            /*!< Transmitter FSM state                                                     */
      __IM  uint32_t TF_COUNT   : 5;            /*!< Number of characters in Transmitter FIFO                                  */
      __IM  uint32_t RX_FSM     : 4;            /*!< Receiver FSM state                                                        */
      __IM  uint32_t RF_COUNT   : 5;            /*!< Number of characters in Receiver FIFO                                     */
      __IM  uint32_t MCR_VAL    : 2;            /*!< Modem Control Register value (bits 4-0)                                   */
      __IM  uint32_t FCR_VAL    : 5;            /*!< FIFO Control Register value (bits 7-6)                                    */
            uint32_t            : 8;
    } DEBUG2_b;
  } ;
} UART_Type;                                    /*!< Size = 40 (0x28)                                                          */


/** @} */ /* End of group Device_Peripheral_peripherals */


/* =========================================================================================================================== */
/* ================                          Device Specific Peripheral Address Map                           ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_peripheralAddr
  * @{
  */

#define SYSCON_BASE                 0x80001000UL
#define SPI_BASE                    0x80001040UL
#define UART_BASE                   0x80002000UL

/** @} */ /* End of group Device_Peripheral_peripheralAddr */


/* =========================================================================================================================== */
/* ================                                  Peripheral declaration                                   ================ */
/* =========================================================================================================================== */


/** @addtogroup Device_Peripheral_declaration
  * @{
  */

#define SYSCON                      ((SYSCON_Type*)            SYSCON_BASE)
#define SPI                         ((SPI_Type*)               SPI_BASE)
#define UART                        ((UART_Type*)              UART_BASE)

/** @} */ /* End of group Device_Peripheral_declaration */


/* =========================================  End of section using anonymous unions  ========================================= */
#if defined (__CC_ARM)
  #pragma pop
#elif defined (__ICCARM__)
  /* leave anonymous unions enabled */
#elif defined(__ARMCC_VERSION) && (__ARMCC_VERSION >= 6010050)
  #pragma clang diagnostic pop
#elif defined (__GNUC__)
  /* anonymous unions are enabled by default */
#elif defined (__TMS470__)
  /* anonymous unions are enabled by default */
#elif defined (__TASKING__)
  #pragma warning restore
#elif defined (__CSMC__)
  /* anonymous unions are enabled by default */
#endif


/* =========================================================================================================================== */
/* ================                                Pos/Mask Peripheral Section                                ================ */
/* =========================================================================================================================== */


/** @addtogroup PosMask_peripherals
  * @{
  */



/* =========================================================================================================================== */
/* ================                                          SYSCON                                           ================ */
/* =========================================================================================================================== */

/* =====================================================  VERSION_PATCH  ===================================================== */
#define SYSCON_VERSION_PATCH_PATCH_Pos    (0UL)                     /*!< PATCH (Bit 0)                                         */
#define SYSCON_VERSION_PATCH_PATCH_Msk    (0xffUL)                  /*!< PATCH (Bitfield-Mask: 0xff)                           */
/* =====================================================  VERSION_MINOR  ===================================================== */
#define SYSCON_VERSION_MINOR_MINOR_Pos    (0UL)                     /*!< MINOR (Bit 0)                                         */
#define SYSCON_VERSION_MINOR_MINOR_Msk    (0xffUL)                  /*!< MINOR (Bitfield-Mask: 0xff)                           */
/* =====================================================  VERSION_MAJOR  ===================================================== */
#define SYSCON_VERSION_MAJOR_MAJOR_Pos    (0UL)                     /*!< MAJOR (Bit 0)                                         */
#define SYSCON_VERSION_MAJOR_MAJOR_Msk    (0xffUL)                  /*!< MAJOR (Bitfield-Mask: 0xff)                           */
/* =====================================================  VERSION_MISC  ====================================================== */
#define SYSCON_VERSION_MISC_REV_Pos       (0UL)                     /*!< REV (Bit 0)                                           */
#define SYSCON_VERSION_MISC_REV_Msk       (0x7fUL)                  /*!< REV (Bitfield-Mask: 0x7f)                             */
#define SYSCON_VERSION_MISC_MODIFIED_Pos  (7UL)                     /*!< MODIFIED (Bit 7)                                      */
#define SYSCON_VERSION_MISC_MODIFIED_Msk  (0x80UL)                  /*!< MODIFIED (Bitfield-Mask: 0x01)                        */
/* ======================================================  VERSION_SHA  ====================================================== */
#define SYSCON_VERSION_SHA_SHA_Pos        (0UL)                     /*!< SHA (Bit 0)                                           */
#define SYSCON_VERSION_SHA_SHA_Msk        (0xffffffffUL)            /*!< SHA (Bitfield-Mask: 0xffffffff)                       */
/* =======================================================  SIM_PRINT  ======================================================= */
#define SYSCON_SIM_PRINT_CHAR_Pos         (0UL)                     /*!< CHAR (Bit 0)                                          */
#define SYSCON_SIM_PRINT_CHAR_Msk         (0xffUL)                  /*!< CHAR (Bitfield-Mask: 0xff)                            */
/* =======================================================  SIM_EXIT  ======================================================== */
#define SYSCON_SIM_EXIT_EXIT_CODE_Pos     (0UL)                     /*!< EXIT_CODE (Bit 0)                                     */
#define SYSCON_SIM_EXIT_EXIT_CODE_Msk     (0xffUL)                  /*!< EXIT_CODE (Bitfield-Mask: 0xff)                       */
/* ======================================================  INIT_STATUS  ====================================================== */
#define SYSCON_INIT_STATUS_RAM_INIT_DONE_Pos (0UL)                  /*!< RAM_INIT_DONE (Bit 0)                                 */
#define SYSCON_INIT_STATUS_RAM_INIT_DONE_Msk (0x1UL)                /*!< RAM_INIT_DONE (Bitfield-Mask: 0x01)                   */
#define SYSCON_INIT_STATUS_RAM_INIT_ERR_Pos (1UL)                   /*!< RAM_INIT_ERR (Bit 1)                                  */
#define SYSCON_INIT_STATUS_RAM_INIT_ERR_Msk (0x2UL)                 /*!< RAM_INIT_ERR (Bitfield-Mask: 0x01)                    */
/* ========================================================  SW_IRQ  ========================================================= */
#define SYSCON_SW_IRQ_SW_IRQ_Pos          (0UL)                     /*!< SW_IRQ (Bit 0)                                        */
#define SYSCON_SW_IRQ_SW_IRQ_Msk          (0xffUL)                  /*!< SW_IRQ (Bitfield-Mask: 0xff)                          */
/* ========================================================  NMI_VEC  ======================================================== */
#define SYSCON_NMI_VEC_VEC_Pos            (0UL)                     /*!< VEC (Bit 0)                                           */
#define SYSCON_NMI_VEC_VEC_Msk            (0xffffffffUL)            /*!< VEC (Bitfield-Mask: 0xffffffff)                       */
/* =========================================================  GPIO0  ========================================================= */
#define SYSCON_GPIO0_PINS_Pos             (0UL)                     /*!< PINS (Bit 0)                                          */
#define SYSCON_GPIO0_PINS_Msk             (0xffffffffUL)            /*!< PINS (Bitfield-Mask: 0xffffffff)                      */
/* =========================================================  GPIO1  ========================================================= */
#define SYSCON_GPIO1_PINS_Pos             (0UL)                     /*!< PINS (Bit 0)                                          */
#define SYSCON_GPIO1_PINS_Msk             (0xffffffffUL)            /*!< PINS (Bitfield-Mask: 0xffffffff)                      */
/* ========================================================  MTIMEL  ========================================================= */
/* ========================================================  MTIMEH  ========================================================= */
/* =======================================================  MTIMECMPL  ======================================================= */
/* =======================================================  MTIMECMPH  ======================================================= */
/* =====================================================  IRQ_TIMER_CNT  ===================================================== */
#define SYSCON_IRQ_TIMER_CNT_CNT_Pos      (0UL)                     /*!< CNT (Bit 0)                                           */
#define SYSCON_IRQ_TIMER_CNT_CNT_Msk      (0xffffffffUL)            /*!< CNT (Bitfield-Mask: 0xffffffff)                       */
/* ====================================================  IRQ_TIMER_CTRL  ===================================================== */
#define SYSCON_IRQ_TIMER_CTRL_CTRL_Pos    (0UL)                     /*!< CTRL (Bit 0)                                          */
#define SYSCON_IRQ_TIMER_CTRL_CTRL_Msk    (0xffUL)                  /*!< CTRL (Bitfield-Mask: 0xff)                            */
/* ======================================================  CLK_FREQ_HZ  ====================================================== */


/* =========================================================================================================================== */
/* ================                                            SPI                                            ================ */
/* =========================================================================================================================== */

/* ==========================================================  CR  =========================================================== */
#define SPI_CR_SPIE_Pos                   (7UL)                     /*!< SPIE (Bit 7)                                          */
#define SPI_CR_SPIE_Msk                   (0x80UL)                  /*!< SPIE (Bitfield-Mask: 0x01)                            */
#define SPI_CR_SPE_Pos                    (6UL)                     /*!< SPE (Bit 6)                                           */
#define SPI_CR_SPE_Msk                    (0x40UL)                  /*!< SPE (Bitfield-Mask: 0x01)                             */
#define SPI_CR_MSTR_Pos                   (4UL)                     /*!< MSTR (Bit 4)                                          */
#define SPI_CR_MSTR_Msk                   (0x10UL)                  /*!< MSTR (Bitfield-Mask: 0x01)                            */
#define SPI_CR_CPOL_Pos                   (3UL)                     /*!< CPOL (Bit 3)                                          */
#define SPI_CR_CPOL_Msk                   (0x8UL)                   /*!< CPOL (Bitfield-Mask: 0x01)                            */
#define SPI_CR_CPHA_Pos                   (2UL)                     /*!< CPHA (Bit 2)                                          */
#define SPI_CR_CPHA_Msk                   (0x4UL)                   /*!< CPHA (Bitfield-Mask: 0x01)                            */
#define SPI_CR_SPR_Pos                    (0UL)                     /*!< SPR (Bit 0)                                           */
#define SPI_CR_SPR_Msk                    (0x3UL)                   /*!< SPR (Bitfield-Mask: 0x03)                             */
/* ==========================================================  SR  =========================================================== */
#define SPI_SR_SPIF_Pos                   (7UL)                     /*!< SPIF (Bit 7)                                          */
#define SPI_SR_SPIF_Msk                   (0x80UL)                  /*!< SPIF (Bitfield-Mask: 0x01)                            */
#define SPI_SR_WCOL_Pos                   (6UL)                     /*!< WCOL (Bit 6)                                          */
#define SPI_SR_WCOL_Msk                   (0x40UL)                  /*!< WCOL (Bitfield-Mask: 0x01)                            */
#define SPI_SR_WFFULL_Pos                 (3UL)                     /*!< WFFULL (Bit 3)                                        */
#define SPI_SR_WFFULL_Msk                 (0x8UL)                   /*!< WFFULL (Bitfield-Mask: 0x01)                          */
#define SPI_SR_WFEMPTY_Pos                (2UL)                     /*!< WFEMPTY (Bit 2)                                       */
#define SPI_SR_WFEMPTY_Msk                (0x4UL)                   /*!< WFEMPTY (Bitfield-Mask: 0x01)                         */
#define SPI_SR_RFFULL_Pos                 (1UL)                     /*!< RFFULL (Bit 1)                                        */
#define SPI_SR_RFFULL_Msk                 (0x2UL)                   /*!< RFFULL (Bitfield-Mask: 0x01)                          */
#define SPI_SR_RFEMPTY_Pos                (0UL)                     /*!< RFEMPTY (Bit 0)                                       */
#define SPI_SR_RFEMPTY_Msk                (0x1UL)                   /*!< RFEMPTY (Bitfield-Mask: 0x01)                         */
/* ==========================================================  DR  =========================================================== */
/* ==========================================================  ER  =========================================================== */
#define SPI_ER_ICNT_Pos                   (6UL)                     /*!< ICNT (Bit 6)                                          */
#define SPI_ER_ICNT_Msk                   (0xc0UL)                  /*!< ICNT (Bitfield-Mask: 0x03)                            */
#define SPI_ER_ESPR_Pos                   (0UL)                     /*!< ESPR (Bit 0)                                          */
#define SPI_ER_ESPR_Msk                   (0x3UL)                   /*!< ESPR (Bitfield-Mask: 0x03)                            */
/* ==========================================================  SS  =========================================================== */


/* =========================================================================================================================== */
/* ================                                           UART                                            ================ */
/* =========================================================================================================================== */

/* ==========================================================  RBR  ========================================================== */
#define UART_RBR_RBR_Pos                  (0UL)                     /*!< RBR (Bit 0)                                           */
#define UART_RBR_RBR_Msk                  (0xffUL)                  /*!< RBR (Bitfield-Mask: 0xff)                             */
/* ==========================================================  THR  ========================================================== */
#define UART_THR_THR_Pos                  (0UL)                     /*!< THR (Bit 0)                                           */
#define UART_THR_THR_Msk                  (0xffUL)                  /*!< THR (Bitfield-Mask: 0xff)                             */
/* ==========================================================  DLL  ========================================================== */
#define UART_DLL_DLL_Pos                  (0UL)                     /*!< DLL (Bit 0)                                           */
#define UART_DLL_DLL_Msk                  (0xffUL)                  /*!< DLL (Bitfield-Mask: 0xff)                             */
/* ==========================================================  IER  ========================================================== */
#define UART_IER_ERBFI_Pos                (0UL)                     /*!< ERBFI (Bit 0)                                         */
#define UART_IER_ERBFI_Msk                (0x1UL)                   /*!< ERBFI (Bitfield-Mask: 0x01)                           */
#define UART_IER_ETBEI_Pos                (1UL)                     /*!< ETBEI (Bit 1)                                         */
#define UART_IER_ETBEI_Msk                (0x2UL)                   /*!< ETBEI (Bitfield-Mask: 0x01)                           */
#define UART_IER_ELSI_Pos                 (2UL)                     /*!< ELSI (Bit 2)                                          */
#define UART_IER_ELSI_Msk                 (0x4UL)                   /*!< ELSI (Bitfield-Mask: 0x01)                            */
#define UART_IER_EDSSI_Pos                (3UL)                     /*!< EDSSI (Bit 3)                                         */
#define UART_IER_EDSSI_Msk                (0x8UL)                   /*!< EDSSI (Bitfield-Mask: 0x01)                           */
/* ==========================================================  DLM  ========================================================== */
#define UART_DLM_DLM_Pos                  (0UL)                     /*!< DLM (Bit 0)                                           */
#define UART_DLM_DLM_Msk                  (0xffUL)                  /*!< DLM (Bitfield-Mask: 0xff)                             */
/* ==========================================================  IIR  ========================================================== */
#define UART_IIR_IPEND_Pos                (0UL)                     /*!< IPEND (Bit 0)                                         */
#define UART_IIR_IPEND_Msk                (0x1UL)                   /*!< IPEND (Bitfield-Mask: 0x01)                           */
#define UART_IIR_INTID_Pos                (1UL)                     /*!< INTID (Bit 1)                                         */
#define UART_IIR_INTID_Msk                (0xeUL)                   /*!< INTID (Bitfield-Mask: 0x07)                           */
#define UART_IIR_FIFOEN_Pos               (6UL)                     /*!< FIFOEN (Bit 6)                                        */
#define UART_IIR_FIFOEN_Msk               (0xc0UL)                  /*!< FIFOEN (Bitfield-Mask: 0x03)                          */
/* ==========================================================  FCR  ========================================================== */
#define UART_FCR_FIFOEN_Pos               (0UL)                     /*!< FIFOEN (Bit 0)                                        */
#define UART_FCR_FIFOEN_Msk               (0x1UL)                   /*!< FIFOEN (Bitfield-Mask: 0x01)                          */
#define UART_FCR_RCVRCLR_Pos              (1UL)                     /*!< RCVRCLR (Bit 1)                                       */
#define UART_FCR_RCVRCLR_Msk              (0x2UL)                   /*!< RCVRCLR (Bitfield-Mask: 0x01)                         */
#define UART_FCR_XMITCLR_Pos              (2UL)                     /*!< XMITCLR (Bit 2)                                       */
#define UART_FCR_XMITCLR_Msk              (0x4UL)                   /*!< XMITCLR (Bitfield-Mask: 0x01)                         */
#define UART_FCR_RXTRIG_Pos               (6UL)                     /*!< RXTRIG (Bit 6)                                        */
#define UART_FCR_RXTRIG_Msk               (0xc0UL)                  /*!< RXTRIG (Bitfield-Mask: 0x03)                          */
/* ==========================================================  LCR  ========================================================== */
#define UART_LCR_WLS_Pos                  (0UL)                     /*!< WLS (Bit 0)                                           */
#define UART_LCR_WLS_Msk                  (0x3UL)                   /*!< WLS (Bitfield-Mask: 0x03)                             */
#define UART_LCR_STB_Pos                  (2UL)                     /*!< STB (Bit 2)                                           */
#define UART_LCR_STB_Msk                  (0x4UL)                   /*!< STB (Bitfield-Mask: 0x01)                             */
#define UART_LCR_PEN_Pos                  (3UL)                     /*!< PEN (Bit 3)                                           */
#define UART_LCR_PEN_Msk                  (0x8UL)                   /*!< PEN (Bitfield-Mask: 0x01)                             */
#define UART_LCR_EPS_Pos                  (4UL)                     /*!< EPS (Bit 4)                                           */
#define UART_LCR_EPS_Msk                  (0x10UL)                  /*!< EPS (Bitfield-Mask: 0x01)                             */
#define UART_LCR_SP_Pos                   (5UL)                     /*!< SP (Bit 5)                                            */
#define UART_LCR_SP_Msk                   (0x20UL)                  /*!< SP (Bitfield-Mask: 0x01)                              */
#define UART_LCR_BC_Pos                   (6UL)                     /*!< BC (Bit 6)                                            */
#define UART_LCR_BC_Msk                   (0x40UL)                  /*!< BC (Bitfield-Mask: 0x01)                              */
#define UART_LCR_DLAB_Pos                 (7UL)                     /*!< DLAB (Bit 7)                                          */
#define UART_LCR_DLAB_Msk                 (0x80UL)                  /*!< DLAB (Bitfield-Mask: 0x01)                            */
/* ==========================================================  MCR  ========================================================== */
#define UART_MCR_DTR_Pos                  (0UL)                     /*!< DTR (Bit 0)                                           */
#define UART_MCR_DTR_Msk                  (0x1UL)                   /*!< DTR (Bitfield-Mask: 0x01)                             */
#define UART_MCR_RTS_Pos                  (1UL)                     /*!< RTS (Bit 1)                                           */
#define UART_MCR_RTS_Msk                  (0x2UL)                   /*!< RTS (Bitfield-Mask: 0x01)                             */
#define UART_MCR_OUT1_Pos                 (2UL)                     /*!< OUT1 (Bit 2)                                          */
#define UART_MCR_OUT1_Msk                 (0x4UL)                   /*!< OUT1 (Bitfield-Mask: 0x01)                            */
#define UART_MCR_OUT2_Pos                 (3UL)                     /*!< OUT2 (Bit 3)                                          */
#define UART_MCR_OUT2_Msk                 (0x8UL)                   /*!< OUT2 (Bitfield-Mask: 0x01)                            */
#define UART_MCR_LOOP_Pos                 (4UL)                     /*!< LOOP (Bit 4)                                          */
#define UART_MCR_LOOP_Msk                 (0x10UL)                  /*!< LOOP (Bitfield-Mask: 0x01)                            */
/* ==========================================================  LSR  ========================================================== */
#define UART_LSR_DR_Pos                   (0UL)                     /*!< DR (Bit 0)                                            */
#define UART_LSR_DR_Msk                   (0x1UL)                   /*!< DR (Bitfield-Mask: 0x01)                              */
#define UART_LSR_OE_Pos                   (1UL)                     /*!< OE (Bit 1)                                            */
#define UART_LSR_OE_Msk                   (0x2UL)                   /*!< OE (Bitfield-Mask: 0x01)                              */
#define UART_LSR_PE_Pos                   (2UL)                     /*!< PE (Bit 2)                                            */
#define UART_LSR_PE_Msk                   (0x4UL)                   /*!< PE (Bitfield-Mask: 0x01)                              */
#define UART_LSR_FE_Pos                   (3UL)                     /*!< FE (Bit 3)                                            */
#define UART_LSR_FE_Msk                   (0x8UL)                   /*!< FE (Bitfield-Mask: 0x01)                              */
#define UART_LSR_BI_Pos                   (4UL)                     /*!< BI (Bit 4)                                            */
#define UART_LSR_BI_Msk                   (0x10UL)                  /*!< BI (Bitfield-Mask: 0x01)                              */
#define UART_LSR_THRE_Pos                 (5UL)                     /*!< THRE (Bit 5)                                          */
#define UART_LSR_THRE_Msk                 (0x20UL)                  /*!< THRE (Bitfield-Mask: 0x01)                            */
#define UART_LSR_TEMT_Pos                 (6UL)                     /*!< TEMT (Bit 6)                                          */
#define UART_LSR_TEMT_Msk                 (0x40UL)                  /*!< TEMT (Bitfield-Mask: 0x01)                            */
#define UART_LSR_FIFOERR_Pos              (7UL)                     /*!< FIFOERR (Bit 7)                                       */
#define UART_LSR_FIFOERR_Msk              (0x80UL)                  /*!< FIFOERR (Bitfield-Mask: 0x01)                         */
/* ==========================================================  MSR  ========================================================== */
#define UART_MSR_DCTS_Pos                 (0UL)                     /*!< DCTS (Bit 0)                                          */
#define UART_MSR_DCTS_Msk                 (0x1UL)                   /*!< DCTS (Bitfield-Mask: 0x01)                            */
#define UART_MSR_DDSR_Pos                 (1UL)                     /*!< DDSR (Bit 1)                                          */
#define UART_MSR_DDSR_Msk                 (0x2UL)                   /*!< DDSR (Bitfield-Mask: 0x01)                            */
#define UART_MSR_TERI_Pos                 (2UL)                     /*!< TERI (Bit 2)                                          */
#define UART_MSR_TERI_Msk                 (0x4UL)                   /*!< TERI (Bitfield-Mask: 0x01)                            */
#define UART_MSR_DDCD_Pos                 (3UL)                     /*!< DDCD (Bit 3)                                          */
#define UART_MSR_DDCD_Msk                 (0x8UL)                   /*!< DDCD (Bitfield-Mask: 0x01)                            */
#define UART_MSR_CTS_Pos                  (4UL)                     /*!< CTS (Bit 4)                                           */
#define UART_MSR_CTS_Msk                  (0x10UL)                  /*!< CTS (Bitfield-Mask: 0x01)                             */
#define UART_MSR_DSR_Pos                  (5UL)                     /*!< DSR (Bit 5)                                           */
#define UART_MSR_DSR_Msk                  (0x20UL)                  /*!< DSR (Bitfield-Mask: 0x01)                             */
#define UART_MSR_RI_Pos                   (6UL)                     /*!< RI (Bit 6)                                            */
#define UART_MSR_RI_Msk                   (0x40UL)                  /*!< RI (Bitfield-Mask: 0x01)                              */
#define UART_MSR_DCD_Pos                  (7UL)                     /*!< DCD (Bit 7)                                           */
#define UART_MSR_DCD_Msk                  (0x80UL)                  /*!< DCD (Bitfield-Mask: 0x01)                             */
/* ========================================================  DEBUG1  ========================================================= */
#define UART_DEBUG1_LSR_VAL_Pos           (0UL)                     /*!< LSR_VAL (Bit 0)                                       */
#define UART_DEBUG1_LSR_VAL_Msk           (0xffUL)                  /*!< LSR_VAL (Bitfield-Mask: 0xff)                         */
#define UART_DEBUG1_IER_VAL_Pos           (8UL)                     /*!< IER_VAL (Bit 8)                                       */
#define UART_DEBUG1_IER_VAL_Msk           (0xf00UL)                 /*!< IER_VAL (Bitfield-Mask: 0x0f)                         */
#define UART_DEBUG1_IIR_VAL_Pos           (12UL)                    /*!< IIR_VAL (Bit 12)                                      */
#define UART_DEBUG1_IIR_VAL_Msk           (0xf000UL)                /*!< IIR_VAL (Bitfield-Mask: 0x0f)                         */
#define UART_DEBUG1_LCR_VAL_Pos           (16UL)                    /*!< LCR_VAL (Bit 16)                                      */
#define UART_DEBUG1_LCR_VAL_Msk           (0xff0000UL)              /*!< LCR_VAL (Bitfield-Mask: 0xff)                         */
#define UART_DEBUG1_MSR_VAL_Pos           (24UL)                    /*!< MSR_VAL (Bit 24)                                      */
#define UART_DEBUG1_MSR_VAL_Msk           (0xff000000UL)            /*!< MSR_VAL (Bitfield-Mask: 0xff)                         */
/* ========================================================  DEBUG2  ========================================================= */
#define UART_DEBUG2_TX_FSM_Pos            (0UL)                     /*!< TX_FSM (Bit 0)                                        */
#define UART_DEBUG2_TX_FSM_Msk            (0x7UL)                   /*!< TX_FSM (Bitfield-Mask: 0x07)                          */
#define UART_DEBUG2_TF_COUNT_Pos          (3UL)                     /*!< TF_COUNT (Bit 3)                                      */
#define UART_DEBUG2_TF_COUNT_Msk          (0xf8UL)                  /*!< TF_COUNT (Bitfield-Mask: 0x1f)                        */
#define UART_DEBUG2_RX_FSM_Pos            (8UL)                     /*!< RX_FSM (Bit 8)                                        */
#define UART_DEBUG2_RX_FSM_Msk            (0xf00UL)                 /*!< RX_FSM (Bitfield-Mask: 0x0f)                          */
#define UART_DEBUG2_RF_COUNT_Pos          (12UL)                    /*!< RF_COUNT (Bit 12)                                     */
#define UART_DEBUG2_RF_COUNT_Msk          (0x1f000UL)               /*!< RF_COUNT (Bitfield-Mask: 0x1f)                        */
#define UART_DEBUG2_MCR_VAL_Pos           (17UL)                    /*!< MCR_VAL (Bit 17)                                      */
#define UART_DEBUG2_MCR_VAL_Msk           (0x60000UL)               /*!< MCR_VAL (Bitfield-Mask: 0x03)                         */
#define UART_DEBUG2_FCR_VAL_Pos           (19UL)                    /*!< FCR_VAL (Bit 19)                                      */
#define UART_DEBUG2_FCR_VAL_Msk           (0xf80000UL)              /*!< FCR_VAL (Bitfield-Mask: 0x1f)                         */

/** @} */ /* End of group PosMask_peripherals */


#ifdef __cplusplus
}
#endif

#endif /* EH2_H */


/** @} */ /* End of group eh2 */

/** @} */ /* End of group Syntronix Corp. */
